name: talenWF
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - biopython>=1.80
  - pandas>=2.0.0
  - numpy>=1.20.0
  - pip
  - pip:
    # Development dependencies
    - pytest>=6.0
    - pytest-cov>=2.0
    - black>=22.0
    - flake8>=4.0
    - build>=1.0.0
    - twine>=4.0.0
    # Install talenWF in editable mode
    - -e .

